SET NAMES 'UTF8MB4';
SET TIME_ZONE = 'Asia/Calcutta';
SET TIME_ZONE = '+5:30';

DROP SCHEMA  securecapita;
CREATE SCHEMA IF NOT EXISTS securecapita;

USE securecapita;


DROP TABLE IF EXISTS Users;

CREATE TABLE Users
(
        user_id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        first_name VARCHAR(50) NOT NULL,
        last_name  VARCHAR(50) NOT NULL,
        email      VARCHAR(100) NOT NULL,
        password   VARCHAR(255) DEFAULT NULL,
        address    VARCHAR(255) DEFAULT NULL,
        phone      VARCHAR(30) DEFAULT NULL,
        title      VARCHAR(50) DEFAULT NULL,
        bio        VARCHAR(255) DEFAULT NULL,
        enabled    BOOLEAN DEFAULT FALSE,
        non_locked BOOLEAN DEFAULT TRUE,
        using_mfa  BOOLEAN DEFAULT FALSE,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        image_url  VARCHAR(255) DEFAULT 'https://cdn-icons-png.flaticon.com/512/149/149071.png',
        CONSTRAINT UQ_Users_Email UNIQUE (email)
);

DROP TABLE IF EXISTS Roles;

CREATE TABLE  Roles
(
    role_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    permissions VARCHAR(245) NOT NULL,
    CONSTRAINT UQ_Roles_Name UNIQUE (name)
);

DROP TABLE IF EXISTS UserRoles;

CREATE TABLE  UserRoles
(
    id      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    users_user_id BIGINT UNSIGNED NOT NULL,
    roles_role_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (users_user_id) REFERENCES Users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (roles_role_id) REFERENCES Roles (role_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT UQ_UserRoles_Users_User_Id UNIQUE (users_user_id)
);

DROP TABLE IF EXISTS Events;

CREATE TABLE  Events
(
    event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type        VARCHAR(50) NOT NULL CHECK(type IN ('LOGIN_ATTEMPT', 'LOGIN_ATTEMPT_FAILURE', 'LOGIN_ATTEMPT_SUCCESS', 'PROFILE_UPDATE', 'PROFILE_PICTURE_UPDATE', 'ROLE_UPDATE', 'ACCOUNT_SETTINGS_UPDATE', 'PASSWORD_UPDATE', 'MFA_UPDATE')),
    description VARCHAR(255) NOT NULL,
    CONSTRAINT UQ_Events_Type UNIQUE(type)
);

DROP TABLE IF EXISTS UserEvents;

CREATE TABLE  UserEvents
(
    user_event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    users_user_id BIGINT UNSIGNED NOT NULL,
    roles_role_id BIGINT UNSIGNED NOT NULL,
    device VARCHAR(50) DEFAULT NULL,
    ip_address VARCHAR(50) DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (users_user_id) REFERENCES Users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (roles_role_id) REFERENCES Roles (role_id) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS AccountVerifications;

CREATE TABLE AccountVerifications
(
    account_verification_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    users_user_id BIGINT UNSIGNED NOT NULL,
    --date DATETIME NOT NULL,
    url VARCHAR(255) NOT NULL,
    FOREIGN KEY (users_user_id) REFERENCES Users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT UQ_AccountVerifications_users_user_id UNIQUE(users_user_id),
    CONSTRAINT UQ_AccountVerifications_Url UNIQUE(url)
);

DROP TABLE IF EXISTS ResetPasswordVerifications;

CREATE TABLE ResetPasswordVerifications
(
    reset_password_verification_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    users_user_id BIGINT UNSIGNED NOT NULL,
    expiration_date DATETIME NOT NULL,
    url VARCHAR(255) NOT NULL,
    FOREIGN KEY (users_user_id) REFERENCES Users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT UQ_ResetPasswordVerifications_users_user_id UNIQUE(users_user_id),
    CONSTRAINT UQ_ResetPasswordVerifications_Url UNIQUE(url)
);

DROP TABLE IF EXISTS TwoFactorVerifications;

CREATE TABLE TwoFactorVerifications
(
    two_factor_verification_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    users_user_id BIGINT UNSIGNED NOT NULL,
    expiration_date DATETIME NOT NULL,
    code VARCHAR(10) NOT NULL,
    FOREIGN KEY (users_user_id) REFERENCES Users (user_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT UQ_TwoFactorVerifications_users_user_id UNIQUE(users_user_id),
    CONSTRAINT UQ_TwoFactorVerifications_Code UNIQUE(code)
);

INSERT INTO Roles (name, permissions)
VALUES ('ROLE_USER' , 'READ:USER, READ:CUSTOMER'),
('ROLE_MANAGER', 'READ:USER,READ:CUSTOMER,UPDATE:USER,UPDATE:CUSTOMER'),
('ROLE_ADMIN', 'READ:USER,READ:CUSTOMER,UPDATE:USER,UPDATE:CUSTOMER, CREATE:USER, CREATE:CUSTOMER'),
('ROLE_SYSADMIN', 'READ:USER,READ:CUSTOMER,UPDATE:USER,UPDATE:CUSTOMER, CREATE:USER, CREATE:CUSTOMER, DELETE:USER, DELETE:CUSTOMER');

